# This is a basic workflow to help you get started with Actions

name: Second_WorkFlow

# Controls when the workflow will run
on:


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  first-job: 
    runs-on: ubuntu-latest
    steps: 
    - name : Just print some output
      run: |
        echo "This is the first line"
        echo "Second line output"
        
  
    
